export interface ChangelogEntry {
  version: string
  date: string
  title: string
  description: string
  changes: string[]
  aiTools: string[]
  branch?: string
  pr?: string
  image?: string
  images?: string[]
}

// Changelog entries - newest first
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.4.1',
    date: '2026-02-08',
    title: 'Homepage Commit Count',
    description: 'Added total commit count above the GitHub contribution graph on the homepage to make the data more personal and impressive.',
    changes: [
      'Computed total commits from the last 12 months of contribution data',
      'Displayed commit count with animation above the contribution graph in the full variant',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/homepage-commit-count',
  },
  {
    version: '1.4.0',
    date: '2026-02-08',
    title: '2x2 Bento Projects Grid',
    description: 'Replaced the horizontal auto-scrolling projects carousel with a 2x2 bento grid showcasing 4 curated case studies with SVG illustrations.',
    changes: [
      'Replaced horizontal carousel with 2x2 bento grid layout (responsive: stacks on mobile)',
      'Added themed SVG illustrations per card: GitHub heatmap, code brackets, workflow nodes, sparkle',
      'Curated 4 featured projects: The Future is Now, Respond to RFP, How I Work, Conjure Your Own Tools',
      'Added numbered cards (01-04) and "View all" link to /projects',
      'Removed carousel auto-scroll, dot indicators, and related state management',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/bento-projects-grid',
  },
  {
    version: '1.3.0',
    date: '2026-02-06',
    title: 'Interactive Hero & Scroll Animations',
    description: 'Added an interactive particle constellation canvas to the hero section, magnetic hover effects on CTAs, and converted all below-fold sections to scroll-triggered reveal animations.',
    changes: [
      'Built canvas-based particle field with organic flow, mouse attraction, spotlight glow, and accent-color-aware rendering',
      'Particles connect with distance-based lines and pulse with breathing opacity',
      'Added Magnetic wrapper component for satisfying cursor-follow hover effects on buttons',
      'Converted About, Projects, Experience, Thinkers, and Testimonials to scroll-triggered `whileInView` animations',
      'Respects `prefers-reduced-motion` and adapts particle count for mobile devices',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/wow-interactive-hero',
  },
  {
    version: '1.2.0',
    date: '2026-02-05',
    title: 'Feed View',
    description: 'Added a new /feed route that aggregates all content types into a filterable, scrollable feed.',
    changes: [
      'Created /feed page with vertical scrollable feed of all content',
      'Unified feed items from projects, thinkers, and changelog entries',
      'Added sticky filter bar with content type and tag filtering',
      'Created FeedCard component with type-specific rendering',
      'Extracted CHANGELOG to shared /src/content/changelog.ts',
      'Added Feed link to Header navigation',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/mobile-feed-view',
  },
  {
    version: '1.1.0',
    date: '2026-02-05',
    title: 'New Essay: You Can Conjure Your Own Tools Now',
    description: 'Added a new article about how AI coding tools change creative practice — building custom tools on demand and preserving design iterations as living artifacts.',
    changes: [
      'Published essay on creative tooling and the shift from waiting for features to conjuring them',
      'Explores using feature branches and flags as a design canvas for iteration history',
      'New project entry accessible from the projects page',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/creative-tooling-post',
  },
  {
    version: '1.0.0',
    date: '2026-02-05',
    title: 'New Essay: The GUI Has to Earn Its Place',
    description: 'Added a new article exploring how chat interfaces are changing expectations for GUIs. Chat API now supports Anthropic for production.',
    changes: [
      'Published essay on changing expectations for GUIs in the age of chat',
      'New project entry accessible from the projects page',
      'Chat API supports Anthropic Haiku 4.5 in production, Groq in dev',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/Gui-essay',
  },
  {
    version: '0.9.0',
    date: '2026-02-05',
    title: 'Product Thinkers',
    description: 'Added a new section showcasing product thinkers who have shaped my approach to design and product work.',
    changes: [
      'Created `/thinkers` page with edge-touching card grid',
      'Added homepage preview section between Experience and Testimonials',
      'Features Teresa Torres, Spiek & Moesta, Ryan Singer, and Christopher Alexander',
      'Created thinkers content data model in `/src/content/thinkers.ts`',
      'Created reusable `ThinkerCard` component for homepage use',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/product-thinkers-page',
  },
  {
    version: '0.8.0',
    date: '2026-02-05',
    title: 'RFP Case Study',
    description: 'Built out the "Responding to an RFP" case study page with full narrative content and video placeholders for key feature demonstrations.',
    changes: [
      'Rewrote RFP case study with full narrative: situation, problem, approach, impact, and outcome',
      'Added TLDR section summarizing the one-person-army story',
      'Added 5 video placeholder sections for key feature demos (seed data, LLM chat, scale adaptation, rapid iteration, interactive workflows)',
      'Structured before/after impact comparison (without AI vs with AI)',
      'Updated project tags, description, and chat context for richer AI sidebar conversations',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/rfp-case-study',
  },
  {
    version: '0.7.0',
    date: '2026-01-24',
    title: 'Edge-Touching Cards & Feature Flags',
    description: 'Major visual refinement with cleaner card layouts and developer tools for design iteration.',
    changes: [
      'Implemented edge-touching card style (no gaps, shared borders)',
      'Added feature flag system with Cmd+K drawer for toggling design options',
      'Created shared GitHubContributions component for reuse across pages',
      'Testimonials now show as horizontal carousel (2 visible at a time)',
      'Projects page matches homepage shell styling with border-x',
      'Section title borders toggleable via feature flag',
      'Removed chat input border for cleaner alignment',
      'Added Experience section with timeline visualization',
      'Added Testimonials section with colleague quotes',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
    images: [
      '/blog/v7-homepage-light.png',
      '/blog/v7-homepage-dark.png',
      '/blog/v7-projects-light.png',
      '/blog/v7-projects-dark.png',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-01-24',
    title: 'Theme System Overhaul & System Mode',
    description: 'Complete redesign of theming with accent colors and system preference support.',
    changes: [
      'Added theme dropdown with System/Day/Night mode options',
      'System mode automatically follows OS light/dark preference',
      'Added 16 Tailwind accent colors (amber, orange, red, rose, etc.)',
      'Accent color persists to localStorage',
      'Real-time system preference change detection',
      'Default to System mode with Amber accent',
    ],
    aiTools: ['Claude Code'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.5.0',
    date: '2026-01-24',
    title: 'ElevenLabs UI & Shimmering Effects',
    description: 'Integrated ElevenLabs UI components for enhanced loading states.',
    changes: [
      'Added ShimmeringText component for loading states',
      'TLDR generation button shows shimmering "Generating summary..." text',
      'Chat interface uses shimmering "Thinking..." for AI responses',
      'Smooth shimmer animation with customizable colors',
    ],
    aiTools: ['Claude Code', 'ElevenLabs'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.4.0',
    date: '2026-01-24',
    title: 'Chat Enhancements & Shared Components',
    description: 'Added project cards in chat and extracted shared components.',
    changes: [
      'Chat can now include project cards using [[project:id]] syntax',
      'Created shared Header component for consistent navigation',
      'Added hover accent colors on project card titles and arrows',
      'Fixed scroll-to-top behavior on article pages',
      'Added "Back to top" button in footers',
      'Fixed double border issues between sections',
      'Fixed dropdown transparency with proper bg-background',
    ],
    aiTools: ['Claude Code'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.3.0',
    date: '2026-01-24',
    title: 'Two-Column Layout & Chat Sidebar',
    description: 'Major redesign focusing on storytelling and AI transformation narrative.',
    changes: [
      'Redesigned to two-column layout (main content + chat sidebar)',
      'Added "Gareth Chainey" as permanent title with animated role subtitle',
      'Created GitHub contributions visualization showing 2024→2025 transformation',
      'Implemented experience timeline with brand-colored highlights',
      'Updated chat interface with black bubbles in day mode',
      'Added Lucide icons for theme toggle (Sun/Moon)',
    ],
    aiTools: ['Claude Code', 'Agentation'],
    branch: 'feature/layout-v2-two-column-chat',
    pr: 'https://github.com/GChainey/portfolioWebsite/pull/2',
  },
  {
    version: '0.2.0',
    date: '2026-01-24',
    title: 'Theme System & GitHub Integration',
    description: 'Added dark/light mode theming and live GitHub activity feed.',
    changes: [
      'Implemented ThemeContext with system preference detection',
      'Added localStorage persistence for theme choice',
      'Created GitHubActivity component fetching live data',
      'Built contribution graph visualization',
      'Added recent activity feed with formatted dates',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
  },
  {
    version: '0.1.0',
    date: '2026-01-24',
    title: 'Initial Scaffolding',
    description: 'Set up the foundational project structure with Next.js 14.',
    changes: [
      'Initialized Next.js 14 with TypeScript and Tailwind CSS',
      'Configured Framer Motion for animations',
      'Set up Anthropic SDK for AI chat integration',
      'Created edge-to-edge grid layout system',
      'Built initial component structure',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
    image: '/blog/v1-grid-layout.png',
  },
]
