export interface ChangelogEntry {
  version: string
  date: string
  title: string
  description: string
  changes: string[]
  aiTools: string[]
  branch?: string
  pr?: string
  image?: string
  images?: string[]
}

// Changelog entries - newest first
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.11.1',
    date: '2026-02-13',
    title: 'Remove Thinker Name Hover Effect',
    description: 'Removed misleading hover styling from product thinker names since the cards are not clickable.',
    changes: [
      'Removed group-hover:text-accent from thinker name heading',
      'Removed group class from ThinkerCard container',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-thinker-hover',
  },
  {
    version: '1.11.0',
    date: '2026-02-13',
    title: 'Live GitHub Contribution Count',
    description: 'Contribution count now syncs live from the GitHub GraphQL API while the heatmap keeps its narrative arc.',
    changes: [
      'Contribution count fetches live total (public + private) from GitHub API',
      'Changed label from "commits" to "contributions" to match GitHub terminology',
      'Removed duplicate CONTRIBUTION_MONTHS from project detail page, uses shared component',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/live-github-commits',
  },
  {
    version: '1.10.4',
    date: '2026-02-13',
    title: 'Subtler Chat Bubbles',
    description: 'Chat message backgrounds now use a color-mix approach for a subtler appearance in both light and dark mode.',
    changes: [
      'Replaced flat bg-border with color-mix(foreground 5%, background) for assistant messages',
      'Dark mode: barely lifted off the dark surface instead of noticeable grey',
      'Light mode: near-white instead of wireframe grey',
      'Applied to welcome message, conversation bubbles, and loading state',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-dark-msg-color',
  },
  {
    version: '1.10.3',
    date: '2026-02-13',
    title: 'Softer CTA Buttons in Dark Mode',
    description: 'Reduced brightness of primary CTA buttons in dark mode for a less harsh appearance against the dark background.',
    changes: [
      'Added --accent-cta CSS variable that darkens the accent by 15% in dark mode',
      'Applied to all primary CTA buttons across homepage, CV, contact, projects, and content dialogs',
      'Light mode CTA buttons remain unchanged',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/darker-cta-dark-mode',
  },
  {
    version: '1.10.2',
    date: '2026-02-12',
    title: 'Experience Dialog Two-Column Layout & Inline Case Studies',
    description: 'Restructured the experience dialog to a two-column layout with full-height chat, and replaced project card links with inline scrollable case study sections.',
    changes: [
      'Changed dialog from stacked (header/content/footer) to two-column layout',
      'Column 1 contains header tabs and scrollable content',
      'Column 2 (GarethLLM chat) now spans the full height of the dialog',
      'Moved close button into the chat panel header',
      'Removed redundant footer navigation since tab group already handles company switching',
      'Replaced project card grid with inline case study sections per project',
      'Each case study has title, description, hero image, detail screenshots, and workflow placeholders',
      'Added View full case study links for each project',
      'Dialog background slightly lighter than base layer for elevated surface feel',
      'Added "Work Experience" title to dialog header',
      'Company tabs now sticky at top of scrollable content',
      'Removed separator from GarethLLM chat header',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/experience-dialog-layout',
  },
  {
    version: '1.10.1',
    date: '2026-02-13',
    title: 'LinkedIn Links on Testimonials',
    description: 'Colleague names in the testimonial carousel now link to their LinkedIn profiles.',
    changes: [
      'Added LinkedIn URLs to all five testimonial entries',
      'Testimonial names render as links that open LinkedIn in a new tab',
      'Hover state uses accent color for consistency with site theme',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/linkedin-testimonials',
  },
  {
    version: '1.10.0',
    date: '2026-02-12',
    title: 'Facehash Chat Avatars',
    description: 'Added deterministic facehash avatars to the GarethLLM chat. Gareth gets a consistent avatar, and visitors get their own unique face after telling GarethLLM their name.',
    changes: [
      'Integrated facehash package for deterministic avatar generation from names',
      'Gareth avatar (with blinking eyes) shown on all assistant messages and loading state',
      'GarethLLM welcome message asks visitors for their name',
      'Name extraction via [[name:X]] tag parsed from LLM responses',
      'Visitor name persisted in localStorage — returning visitors get greeted by name',
      'Visitor facehash avatar appears on their messages once name is known',
      'All existing suggested and follow-up questions preserved',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/facehash-chat-avatars',
  },
  {
    version: '1.9.0',
    date: '2026-02-12',
    title: 'Experience Dialog Carousel',
    description: 'Clickable company names in the Experience section now open a dialog carousel showing company synopsis, key achievements, and related case study links.',
    changes: [
      'New ExperienceDialog component with carousel navigation between companies',
      'Company names in Experience section are now clickable on both homepage and CV page',
      'View button opens dialog starting at most recent company (EnterpriseAI)',
      'Arrow keys and tab navigation to browse between companies',
      'Added placeholder case studies for Daisy Assist, Daisy Assess, SEEK, and Best Practice',
      'Projects linked to companies via companyId field',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/experience-case-studies',
  },
  {
    version: '1.8.4',
    date: '2026-02-12',
    title: 'Testimonial Carousel Scroll Indicators',
    description: 'Added dot indicators and arrow navigation to the testimonial carousel for clearer scroll affordance.',
    changes: [
      'Added dot pagination indicators below testimonial cards',
      'Added left/right chevron arrow buttons for navigation',
      'Left arrow hidden when at the start, right arrow hidden at the end',
      'Extracted shared TestimonialCarousel component used on both home and CV pages',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/scroll-indicators',
  },
  {
    version: '1.8.3',
    date: '2026-02-12',
    title: 'GarethLLM Open by Default on All Pages',
    description: 'Chat sidebar now opens immediately on all pages except homepage, which keeps its animation delay.',
    changes: [
      'Thinkers page: chat opens by default instead of after 1.5s delay',
      'Project pages: chat opens by default instead of waiting for useEffect',
      'Mobile: chat still stays closed on small screens',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-open-all-pages',
  },
  {
    version: '1.8.2',
    date: '2026-02-12',
    title: 'Intercom-style Chat Input & Bubbles',
    description: 'Redesigned chat input and message bubbles to match Intercom/Fin style.',
    changes: [
      'Combined input field and send button into a single bordered container',
      'Replaced "Send" text button with a circular ArrowUp icon button',
      'Switched to multiline textarea with auto-resize (Enter to send, Shift+Enter for new line)',
      'Increased chat bubble border radius to match Fin-style rounded bubbles with tail corners',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-input-redesign',
  },
  {
    version: '1.8.1',
    date: '2026-02-12',
    title: 'Auto-open GarethLLM Chat',
    description: 'GarethLLM chat sidebar now automatically opens after the hero typewriter animation and tooltip complete.',
    changes: [
      'Chat opens automatically after Product Orchestrator animation sequence finishes',
      'Removed separate chat mount timer in favor of sequenced timing tied to animation completion',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/auto-open-chat',
  },
  {
    version: '1.8.0',
    date: '2026-02-08',
    title: 'Article Table of Contents',
    description: 'Added a Substack-style table of contents for case study articles with inline collapsible TOC and a fixed sidebar TOC that appears when scrolling.',
    changes: [
      'Inline TOC at top of article with collapsible heading list (Contents toggle)',
      'Fixed sidebar TOC rendered outside main container to avoid overflow clipping',
      'Compact abstract lines on left border indicate sections, expand to full panel on click',
      'Active heading tracking via IntersectionObserver',
      'Click-to-scroll navigation with smooth scrolling',
      'Escape and click-outside to close expanded panel',
      'Responsive: hidden on mobile, visible on lg+ screens',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/article-toc',
  },
  {
    version: '1.7.0',
    date: '2026-02-08',
    title: 'Dynamic GitHub Commit Count',
    description: 'Live commit count fetched from GitHub API with a count-up animation.',
    changes: [
      'Added API route to fetch real contribution count from GitHub GraphQL API',
      'Count-up animation rolls numbers from 0 using framer-motion springs',
      'Server-side caching (1 hour TTL) to avoid GitHub rate limits',
      'Graceful fallback to static count when API is unavailable',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/animate-commit-count',
  },
  {
    version: '1.6.6',
    date: '2026-02-08',
    title: 'Neutral Chat Input Styling',
    description: 'Removed accent color from chat send button and input focus, using Fin-style neutral black/white theming instead.',
    changes: [
      'Send button: black in light mode, white in dark mode; grayed out when disabled',
      'Chat input focus uses standard ring style instead of accent-colored border',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-send-btn-muted',
  },
  {
    version: '1.6.5',
    date: '2026-02-08',
    title: 'Typewriter Hero & Commit Count',
    description: 'Added typewriter role animation on homepage and commit count above the GitHub contribution graph.',
    changes: [
      'Typewriter effect: Designer → Designer? → Engineer? → Orchestrator',
      'Trademark disclaimer tooltip on Orchestrator with shadcn tooltip',
      'Computed and displayed 872 commits in last 12 months above contribution graph',
      'Added GitHub profile outline button next to primary CTA',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/homepage-commit-count',
  },
  {
    version: '1.6.4',
    date: '2026-02-08',
    title: 'Default Dark Mode with No Flash',
    description: 'Changed the default theme to dark mode for a stronger first impression on portfolio visitors, and eliminated the flash of light mode on page load.',
    changes: [
      'Default theme changed from system to dark mode for new visitors',
      'Added inline blocking script to set dark class before first paint, preventing white flash',
      'Server-rendered HTML now includes dark class on html element',
      'Existing user preferences (light/system) are still respected via localStorage',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/default-dark-mode',
  },
  {
    version: '1.6.3',
    date: '2026-02-08',
    title: 'Fix chat sidebar scroll bug',
    description: 'Fixed a bug where opening the chat sidebar caused the main page content to scroll down unexpectedly.',
    changes: [
      'Replaced scrollIntoView() with direct scrollTop manipulation to prevent scroll from bubbling to parent containers',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-chat-scroll-bug',
  },
  {
    version: '1.6.2',
    date: '2026-02-08',
    title: 'Subtle Accent Treatment for Selection & Chat FAB',
    description: 'Replaced bright accent backgrounds with a subtle muted treatment using color-mix() for text selection and the floating chat button.',
    changes: [
      'Added --selection-bg and --selection-text CSS variables using color-mix() for light and dark modes',
      'Text selection now uses muted accent background with medium-toned accent text',
      'Floating chat button across all 6 pages uses the same subtle treatment',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/subtle-text-selection',
  },
  {
    version: '1.6.1',
    date: '2026-02-08',
    title: 'Fix Button Gravity When Particle Field Off',
    description: 'Fixed a bug where the magnetic cursor-pull effect on buttons remained active even when the particle field feature flag was disabled.',
    changes: [
      'Added disabled prop to Magnetic component that resets offset and skips mouse listener',
      'Linked Magnetic disabled state to the particleField feature flag',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-button-gravity',
  },
  {
    version: '1.6.0',
    date: '2026-02-08',
    title: 'Interactive Venn Diagram Skills Section',
    description: 'Replaced the flat skills list with an interactive 3-circle Venn diagram (Product, Design, Engineering) to showcase cross-disciplinary skills.',
    changes: [
      'Moved skills section from below header to just above testimonials',
      'Added interactive SVG Venn diagram with Product, Design, and Engineering circles',
      'Click any region (single, overlap, or center) to filter skills to that intersection',
      'Two-column layout: Venn diagram (2/3) with scrollable skill tags (1/3)',
      'Gradient borders on multi-zone skills using background-clip trick for rounded corners',
      'Multi-zone title shows each zone name in its own color',
      'Scroll-to-top on CV page mount to fix navigation issue',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/cv-skills-reposition',
  },
  {
    version: '1.5.0',
    date: '2026-02-08',
    title: 'Blog → Changelog',
    description: 'Replaced the blog page with a concise changelog. Moved route from /blog to /changelog, stripped the long-form article, and kept just the version timeline.',
    changes: [
      'Renamed /blog route to /changelog',
      'Removed blog article and markdown renderer — page now shows only the version timeline',
      'Updated header nav and feed links to point to /changelog',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/blog-to-changelog',
  },
  {
    version: '1.4.0',
    date: '2026-02-08',
    title: '2x2 Bento Projects Grid',
    description: 'Replaced the horizontal auto-scrolling projects carousel with a 2x2 bento grid showcasing 4 curated case studies with SVG illustrations.',
    changes: [
      'Replaced horizontal carousel with 2x2 bento grid layout (responsive: stacks on mobile)',
      'Added themed SVG illustrations per card: GitHub heatmap, code brackets, workflow nodes, sparkle',
      'Curated 4 featured projects: The Future is Now, Respond to RFP, How I Work, Conjure Your Own Tools',
      'Added numbered cards (01-04) and "View all" link to /projects',
      'Removed carousel auto-scroll, dot indicators, and related state management',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/bento-projects-grid',
  },
  {
    version: '1.3.0',
    date: '2026-02-06',
    title: 'Interactive Hero & Scroll Animations',
    description: 'Added an interactive particle constellation canvas to the hero section, magnetic hover effects on CTAs, and converted all below-fold sections to scroll-triggered reveal animations.',
    changes: [
      'Built canvas-based particle field with organic flow, mouse attraction, spotlight glow, and accent-color-aware rendering',
      'Particles connect with distance-based lines and pulse with breathing opacity',
      'Added Magnetic wrapper component for satisfying cursor-follow hover effects on buttons',
      'Converted About, Projects, Experience, Thinkers, and Testimonials to scroll-triggered `whileInView` animations',
      'Respects `prefers-reduced-motion` and adapts particle count for mobile devices',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/wow-interactive-hero',
  },
  {
    version: '1.2.0',
    date: '2026-02-05',
    title: 'Feed View',
    description: 'Added a new /feed route that aggregates all content types into a filterable, scrollable feed.',
    changes: [
      'Created /feed page with vertical scrollable feed of all content',
      'Unified feed items from projects, thinkers, and changelog entries',
      'Added sticky filter bar with content type and tag filtering',
      'Created FeedCard component with type-specific rendering',
      'Extracted CHANGELOG to shared /src/content/changelog.ts',
      'Added Feed link to Header navigation',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/mobile-feed-view',
  },
  {
    version: '1.1.0',
    date: '2026-02-05',
    title: 'New Essay: You Can Conjure Your Own Tools Now',
    description: 'Added a new article about how AI coding tools change creative practice — building custom tools on demand and preserving design iterations as living artifacts.',
    changes: [
      'Published essay on creative tooling and the shift from waiting for features to conjuring them',
      'Explores using feature branches and flags as a design canvas for iteration history',
      'New project entry accessible from the projects page',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/creative-tooling-post',
  },
  {
    version: '1.0.0',
    date: '2026-02-05',
    title: 'New Essay: The GUI Has to Earn Its Place',
    description: 'Added a new article exploring how chat interfaces are changing expectations for GUIs. Chat API now supports Anthropic for production.',
    changes: [
      'Published essay on changing expectations for GUIs in the age of chat',
      'New project entry accessible from the projects page',
      'Chat API supports Anthropic Haiku 4.5 in production, Groq in dev',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/Gui-essay',
  },
  {
    version: '0.9.0',
    date: '2026-02-05',
    title: 'Product Thinkers',
    description: 'Added a new section showcasing product thinkers who have shaped my approach to design and product work.',
    changes: [
      'Created `/thinkers` page with edge-touching card grid',
      'Added homepage preview section between Experience and Testimonials',
      'Features Teresa Torres, Spiek & Moesta, Ryan Singer, and Christopher Alexander',
      'Created thinkers content data model in `/src/content/thinkers.ts`',
      'Created reusable `ThinkerCard` component for homepage use',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/product-thinkers-page',
  },
  {
    version: '0.8.0',
    date: '2026-02-05',
    title: 'RFP Case Study',
    description: 'Built out the "Responding to an RFP" case study page with full narrative content and video placeholders for key feature demonstrations.',
    changes: [
      'Rewrote RFP case study with full narrative: situation, problem, approach, impact, and outcome',
      'Added TLDR section summarizing the one-person-army story',
      'Added 5 video placeholder sections for key feature demos (seed data, LLM chat, scale adaptation, rapid iteration, interactive workflows)',
      'Structured before/after impact comparison (without AI vs with AI)',
      'Updated project tags, description, and chat context for richer AI sidebar conversations',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/rfp-case-study',
  },
  {
    version: '0.7.0',
    date: '2026-01-24',
    title: 'Edge-Touching Cards & Feature Flags',
    description: 'Major visual refinement with cleaner card layouts and developer tools for design iteration.',
    changes: [
      'Implemented edge-touching card style (no gaps, shared borders)',
      'Added feature flag system with Cmd+K drawer for toggling design options',
      'Created shared GitHubContributions component for reuse across pages',
      'Testimonials now show as horizontal carousel (2 visible at a time)',
      'Projects page matches homepage shell styling with border-x',
      'Section title borders toggleable via feature flag',
      'Removed chat input border for cleaner alignment',
      'Added Experience section with timeline visualization',
      'Added Testimonials section with colleague quotes',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
    images: [
      '/blog/v7-homepage-light.png',
      '/blog/v7-homepage-dark.png',
      '/blog/v7-projects-light.png',
      '/blog/v7-projects-dark.png',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-01-24',
    title: 'Theme System Overhaul & System Mode',
    description: 'Complete redesign of theming with accent colors and system preference support.',
    changes: [
      'Added theme dropdown with System/Day/Night mode options',
      'System mode automatically follows OS light/dark preference',
      'Added 16 Tailwind accent colors (amber, orange, red, rose, etc.)',
      'Accent color persists to localStorage',
      'Real-time system preference change detection',
      'Default to System mode with Amber accent',
    ],
    aiTools: ['Claude Code'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.5.0',
    date: '2026-01-24',
    title: 'ElevenLabs UI & Shimmering Effects',
    description: 'Integrated ElevenLabs UI components for enhanced loading states.',
    changes: [
      'Added ShimmeringText component for loading states',
      'TLDR generation button shows shimmering "Generating summary..." text',
      'Chat interface uses shimmering "Thinking..." for AI responses',
      'Smooth shimmer animation with customizable colors',
    ],
    aiTools: ['Claude Code', 'ElevenLabs'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.4.0',
    date: '2026-01-24',
    title: 'Chat Enhancements & Shared Components',
    description: 'Added project cards in chat and extracted shared components.',
    changes: [
      'Chat can now include project cards using [[project:id]] syntax',
      'Created shared Header component for consistent navigation',
      'Added hover accent colors on project card titles and arrows',
      'Fixed scroll-to-top behavior on article pages',
      'Added "Back to top" button in footers',
      'Fixed double border issues between sections',
      'Fixed dropdown transparency with proper bg-background',
    ],
    aiTools: ['Claude Code'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.3.0',
    date: '2026-01-24',
    title: 'Two-Column Layout & Chat Sidebar',
    description: 'Major redesign focusing on storytelling and AI transformation narrative.',
    changes: [
      'Redesigned to two-column layout (main content + chat sidebar)',
      'Added "Gareth Chainey" as permanent title with animated role subtitle',
      'Created GitHub contributions visualization showing 2024→2025 transformation',
      'Implemented experience timeline with brand-colored highlights',
      'Updated chat interface with black bubbles in day mode',
      'Added Lucide icons for theme toggle (Sun/Moon)',
    ],
    aiTools: ['Claude Code', 'Agentation'],
    branch: 'feature/layout-v2-two-column-chat',
    pr: 'https://github.com/GChainey/portfolioWebsite/pull/2',
  },
  {
    version: '0.2.0',
    date: '2026-01-24',
    title: 'Theme System & GitHub Integration',
    description: 'Added dark/light mode theming and live GitHub activity feed.',
    changes: [
      'Implemented ThemeContext with system preference detection',
      'Added localStorage persistence for theme choice',
      'Created GitHubActivity component fetching live data',
      'Built contribution graph visualization',
      'Added recent activity feed with formatted dates',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
  },
  {
    version: '0.1.0',
    date: '2026-01-24',
    title: 'Initial Scaffolding',
    description: 'Set up the foundational project structure with Next.js 14.',
    changes: [
      'Initialized Next.js 14 with TypeScript and Tailwind CSS',
      'Configured Framer Motion for animations',
      'Set up Anthropic SDK for AI chat integration',
      'Created edge-to-edge grid layout system',
      'Built initial component structure',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
    image: '/blog/v1-grid-layout.png',
  },
]
