export interface ChangelogEntry {
  version: string
  date: string
  title: string
  description: string
  changes: string[]
  aiTools: string[]
  branch?: string
  pr?: string
  image?: string
  images?: string[]
}

// Changelog entries - newest first
export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.30.0',
    date: '2026-10-09',
    title: 'Homepage variants: Show & Think',
    description:
      'Two experimental homepage directions on the existing /variants launch pad for A/B testing hiring replies. Production homepage and main nav unchanged.',
    changes: [
      '/variants/show — visual-first bento with inline company marks, live iframe tiles, and case study cards',
      '/variants/think — AI-native intro with tool icons, Paper-to-live-code demo, decision record cards, and changelog velocity strip',
      'Launch pad index updated; noindex via existing /variants headers plus page metadata',
    ],
    aiTools: ['Cursor'],
    branch: 'cursor/homepage-variants-show-think-67f7',
  },
  {
    version: '1.29.0',
    date: '2026-10-08',
    title: 'The New Homepage Is Live, with the RFP Clips',
    description:
      'The reworked homepage is switched on, and the RFP case study now leads its examples with recordings of the real prototype.',
    changes: [
      'Homepage order: hero, products, three case studies under "How design has changed with AI", experience, kind words, product thinkers, then earlier work, essays and small studies',
      'RFP case study: five clips of the prototype in place (overview, seed data, the council-wording rewrite, a request for information and a determination letter)',
      'RFP case study: a new section on ProductLite, the mocked-up product in code that became the source of truth for demos and for engineering',
      'Configurator opens with a clip of the prototype running on real LLM data',
      'The website case study shows as Coming soon until it is written',
      'Each testimonial carries its company mark: SpaceX, SEEK or Best Practice',
      'Thesis has a real synopsis on its card',
      'Removed the switch that held all of this back, and the published versions it kept alive',
    ],
    aiTools: ['Claude Code'],
  },
  {
    version: '1.28.0',
    date: '2026-10-08',
    title: 'Three Main Projects, and a Quieter Homepage (not live yet)',
    description:
      'The homepage now leads with products and three projects framed around what AI made possible, and closes with lists of essays and case studies. The RFP case study is rewritten as before and now, and the hero button leads there. It is merged but switched off in production until the case study clips are in.',
    changes: [
      'Product cards lose the category and year line, the tags and the status badge, leaving the name, one line and the link',
      'Homepage order: hero, products, three case studies, experience, kind words, product thinkers, then earlier work, essays and small studies',
      'Projects becomes "Case studies: how design has changed with AI", three cards: the RFP response, a website built from an HTML brand, and Configurator',
      'The page closes with three plain lists: Earlier work (SEEK, Best Practice), Essays and Small studies',
      'A new case study stub for the website built with the Little Plains HTML brand approach, and a new opening line for Configurator',
      'The RFP case study is now "One RFP, Two Ways to Answer It": five examples, each shown as a Before and Now pair, at about half the length',
      'A new comparison block for case studies puts two ways of doing the same job side by side',
      'Each RFP example leads with a clip. Until a clip is switched on its slot only shows on the dev server: a labelled placeholder with a brief for what to film, or the clip itself once the file is in the folder',
      'One switch, NEW_HOME_LIVE, holds all of it back: with it off, production renders the homepage and case studies exactly as published',
      'The homepage gallery section is gone. On the dev server a Page / Visuals switch under the hero swaps the whole page for the gallery instead',
      'The hero "Read how" button goes to the RFP study',
    ],
    aiTools: ['Claude Code'],
  },
  {
    version: '1.27.0',
    date: '2026-10-07',
    title: 'Demos (not live yet)',
    description:
      'A single scrolling page of things you can press, as a tighter alternative to the gallery. Each demo is a real prototype in a frame with its controls beside it. Like the gallery, it is switched off in production for now.',
    changes: [
      'A /demos page with six demos: a brand switcher, the installer state machine, a layout toggle, the Add document timelapse, its self-running tour, and three directions for this homepage',
      'Buttons build the URL each prototype already understands, so the page never redraws a screen and every state is a link',
      'Three layouts to compare: a split one with the controls beside each prototype, a document one at /demos/doc that reads like a written page with the options as rows of a table, and a hybrid at /demos/hybrid with the text on the page and the options beside the prototype',
      'A floating dock follows the scroll and jumps between demos',
      'Frames only run while they are near the screen, and stay out of the way of the scroll until you click into one',
      'The scaled prototype frame from the case studies is now a shared component',
      'A local-only /parked page lists everything that is merged but not on the public site (demos, gallery, homepage variants, playground, feed, flagged experiments), with what switches each one on and what is left to decide',
    ],
    aiTools: ['Claude Code'],
  },
  {
    version: '1.26.0',
    date: '2026-10-07',
    title: 'Case Study: Workspace and App Settings',
    description:
      'A new Enterprise AI case study on the logic behind a settings redesign: grouping the parts of the system into features, then making workspace settings and app settings easy to tell apart.',
    changes: [
      'New case study, Two Levels of Settings Without Getting Lost, linked to Enterprise AI',
      'Two before recordings from earlier builds: settings as a list of parts, and app settings and workspace settings looking the same',
      'Three after recordings: the features inside app settings, nested app settings with the colours swapped, and workspace settings as a dialog',
      'A closing section on what AI made possible: working HTML prototypes with real state and seeded tenancies',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/workspace-app-settings-design',
  },
  {
    version: '1.25.0',
    date: '2026-10-07',
    title: 'Shader Wall in Products',
    description:
      'Added Shader Wall to the products section, and made it and Dispatch click out to their live sites, on the homepage and on both homepage variants. Thesis is marked coming soon.',
    changes: [
      'Added Shader Wall as a product, with its app icon, linking to shaderwall.com',
      'Dispatch now clicks out to dispatchmac.com',
      'Product cards no longer link to a case study, the whole card just opens the product',
      'Thesis is marked coming soon and doesn’t link anywhere until it’s ready to share',
      'Dispatch shows its app icon in place of the animated visual',
      'Products sit three across on the homepage and the projects page',
      'Brand and Showcase variants: Shader Wall and Dispatch icons added, and both cards link out',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/shaderwall-website-update',
  },
  {
    version: '1.24.1',
    date: '2026-10-07',
    title: 'SEEK Case Study: Cards, Funnel and Light Mode',
    description:
      'Polish on the SEEK case study: results as cards, a tidier funnel diagram, and screens that no longer sit on black in light mode.',
    changes: [
      'Results are cards instead of a bulleted list: the number, what it measures, and the goal it was up against',
      'Funnel diagram: assumption cards use the accent colour, sit beside their stage and keep clear of the border; the style switcher and the entrance animation are gone',
      'Device screenshots have transparent backgrounds, and phone recordings sit on a panel that follows the theme',
      'Cropped the laptop frame and black borders out of the desktop recordings',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/seek-best-practice-case-studies',
  },
  {
    version: '1.24.0',
    date: '2026-10-07',
    title: 'Gallery (not live yet)',
    description:
      'Built a gallery: a dump of real screens, prototypes and sites in a bento grid, where clicking a tile opens the artefact itself in a large dialog. It is merged but switched off in production while I decide what goes in it.',
    changes: [
      'A /gallery page with group filters, a homepage section and a header link, all local-only for now',
      'Websites get the large tiles; features and interactions get small ones',
      'Tiles open a live prototype you can use, a video or an image',
      'The same gallery is ready for the Brand and Showcase homepage variants, which stay as they are until it goes live',
      'An edit mode with a Share checkbox on every tile, for choosing what is shown',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/bento-grid-gallery-section',
  },
  {
    version: '1.23.0',
    date: '2026-10-07',
    title: 'SEEK and Best Practice Case Studies',
    description:
      'Wrote up two case studies from earlier roles, taken from my portfolio presentation: recovering an underperforming MVP at SEEK, and the two-panel appointment dialog at Best Practice.',
    changes: [
      'SEEK: rewrote the funnel case study to start at the MVP release, with the three fixes, real screens and the results',
      'Best Practice: replaced the placeholder with the full appointment booking story, from the original dialog to the two-panel design',
      'Cropped images out of the presentation slides and pulled 12 screen recordings from them, so the interactions play in the articles',
      'Brand variant: each case study has its own page in that company\'s brand, linked from the work track and the career panels',
      'An article hero can now be a video: the Best Practice piece opens on the final design playing',
      'Experience dialog shows a case study\'s hero image when it has one, instead of placeholder art',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/seek-best-practice-case-studies',
  },
  {
    version: '1.22.0',
    date: '2026-10-06',
    title: 'New Essay: Agentic User Testing',
    description:
      'Published "Agentic user testing" on the site, an essay first posted as an article on X about having an agent set up Lyssna tests and read PostHog results from HTML prototypes.',
    changes: [
      'Added the essay to Writing & case studies with its cover image and the whole-flow diagram',
      'Content lists can now be numbered, for steps where the order matters',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/twitter-article-to-blog',
  },
  {
    version: '1.21.2',
    date: '2026-10-05',
    title: 'Add Document Case Study: Hero Image',
    description:
      'Added a hero image to the Add document case study: a rule selected in the dialog, with the part of the driver\'s license it checks lit up in purple.',
    changes: [
      'Captured the hero from the live prototype at 2x, with "Holder is 18 or over" selected and date of birth highlighted',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/add-document-hero',
  },
  {
    version: '1.21.1',
    date: '2026-10-05',
    title: 'Add Document Case Study: Shorter Ending',
    description:
      'Trimmed the end of the Add document case study so it finishes on the timelapse.',
    changes: [
      'Removed the round-by-round data card, the closing paragraph and the "What I took from it" list',
      'Removed the now-unused IterationLog component',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/add-document-trim-ending',
  },
  {
    version: '1.21.0',
    date: '2026-10-02',
    title: 'Add Document Case Study',
    description:
      'New case study on the Add document dialog for AI Document Review, with the live state machine embedded on a canvas and an interactive log of all 27 rounds of feedback.',
    changes: [
      'Brought the state machine prototype across as static HTML under /case-studies/add-document',
      'DemoCanvas component: a live prototype on a dotted canvas, scaled to fit, with Explore, Feature demo and State machine tour modes',
      'IterationTimelapse component: scrub or play through 23 real screenshots of the dialog, one per round of feedback, with the feedback that caused each change',
      'IterationLog component: every round of feedback as a column of changes, filterable by theme, with the original feedback and what changed',
      'Drafted the story: the problem, the preview, the state machine and what 27 rounds of tinkering with AI looked like',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/html-demos-blog-post',
  },
  {
    version: '1.20.2',
    date: '2026-09-29',
    title: 'Vercel Web Analytics',
    description:
      'Added Vercel Web Analytics so pageviews are recorded in production after deploy.',
    changes: [
      'Installed @vercel/analytics and mounted Analytics in the root layout',
    ],
    aiTools: ['Cursor'],
    branch: 'cursor/vercel-web-analytics-68d8',
  },
  {
    version: '1.20.1',
    date: '2026-09-29',
    title: 'AI Chat Fix and Spend Cap',
    description:
      'Fixed the production AI chat, which was calling a Claude model ID that does not exist, and added a monthly spend cap plus abuse protection.',
    changes: [
      'Corrected the production model to claude-haiku-4-5-20251001',
      'Monthly spend cap (default $10, set via CHAT_MONTHLY_CAP_USD) tracked in Upstash Redis from real token usage; chat pauses with a friendly message once reached',
      'Per-IP rate limit (20 messages an hour), and caps on history length, message length and system prompt size',
      'Production now fails closed when the API key or Redis is missing instead of silently falling back to Groq',
      'Chat UI shows the server’s friendly limit messages instead of a generic error',
    ],
    aiTools: ['Claude Code'],
  },
  {
    version: '1.20.0',
    date: '2026-09-27',
    title: 'Homepage Variants Launch Pad',
    description:
      'Added an unlisted /variants launch pad with two alternative homepage directions, built as static HTML prototypes, alongside the current site. The live homepage is unchanged.',
    changes: [
      '/variants launch pad: A · Original (the current site), B · Brand and C · Showcase',
      'B · Brand (/variants/brand): full-bleed brand-led layout; career chapters as horizontally scrolling, full-viewport panels in each company’s brand; testimonials carry each colleague’s company branding; Dispatch, Shaders and Thesis product cards with a live, shuffleable shader; day/night mode',
      'C · Showcase (/variants/showcase): work-first layout built from real prototype screenshots, a featured product stage, case studies and a filterable wall of screens',
      'Served from public/variants via Next rewrites for clean URLs, with noindex headers and meta tags so they stay out of search',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/variants-launchpad',
  },
  {
    version: '1.19.2',
    date: '2026-09-25',
    title: 'Experience: Lead Product Designer at Enterprise AI, NYC',
    description:
      'Consolidated current experience into a single role: Lead Product Designer at Enterprise AI, now based in New York City.',
    changes: [
      'Removed the separate ADAPTOVATE role from the CV data, homepage experience timeline and career Lifeline',
      'Enterprise AI is now Lead Product Designer, May 2025 – Present, based in New York City',
      'CV location updated to New York City, USA',
      'Experience dialog and "View" buttons default to Enterprise AI',
      'Chat context (llmContext) updated so the assistant describes the current role correctly',
      'Lifeline 2026 milestone now covers the move to New York City and the app-builder prototyping work',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/consolidate-enterprise-ai',
  },
  {
    version: '1.19.1',
    date: '2026-09-25',
    title: 'Real GitHub Heatmap',
    description:
      'The homepage heatmap was a hand-drawn Jan 2024 – Jun 2025 narrative. It now plots real contributions for the last 24 months, and the headline count no longer double counts private work.',
    changes: [
      '/api/github now returns daily contributions for the last two years (two aliased one-year contributionsCollection windows) alongside the 12-month total',
      'Fixed the total double counting: the viewer calendar already includes private contributions, so restrictedContributionsCount is no longer added on top',
      'Heatmap columns are months and rows are weekdays, with GitHub-style quartile levels. Each column has a hover title with that month’s total',
      'Range label reads "Oct 2024 → Now" and moves forward automatically each month',
      'Static fallback replaced with a snapshot of real data, used until the API responds or if it fails',
      'One shared request for every heatmap on the page; hooks no longer called after early returns',
      'Full heatmap uses smaller cells under the sm breakpoint so 24 months fit on mobile',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/portfolio-html-redesigns',
  },
  {
    version: '1.19.0',
    date: '2026-08-11',
    title: 'Playground Sandbox & Lifeline Timeline',
    description:
      'Added an unlisted /playground route for trialling components before they land on the site, and installed evilrabbit/lifeline as its first specimen — a scrub-along career timeline fed from the CV.',
    changes: [
      'New /playground route with a specimen switcher, viewport presets (full/1280/768/390) and a bounds outline toggle',
      'Specimens registered in a single src/app/playground/specimens.tsx file; stage remounts on switch so entry animations replay',
      'Installed evilrabbit/lifeline from its shadcn registry (npx shadcn add evilrabbit/lifeline/lifeline)',
      'Career timeline data in src/content/lifeline-career.ts, sourced from src/content/cv.ts',
      'Hoisted Lifeline keyframes out of the registry’s Tailwind v4 @theme block — this project is on Tailwind 3.4, where that at-rule is dropped along with its contents',
      'Pointed --lifeline-font at the site’s Inter instead of Geist so the timeline matches surrounding typography',
      'Set tsconfig target to ES2017; the registry iterates a Map, which fails to typecheck against the previous ES5 default',
      'Suppressed Lifeline age labels — this is a career axis, not a life, so year-minus-birthYear would read as a wrong age',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/playground-section',
  },
  {
    version: '1.18.0',
    date: '2026-08-11',
    title: 'Products Section',
    description: 'Added a Products section for things I\'ve built and shipped — each one gets its own case study and can link out to the live product.',
    changes: [
      'New Products section on the home page and at the top of /projects',
      'Added Dispatch and Thesis as the first two products, with case studies marked coming soon',
      'New ProductCard component with animated accent SVG visuals and a Live status badge',
      'Cards carry two destinations — a stretched link to the case study, plus a separate link out to the live product once a URL is set',
      'Product case studies show a "Visit <product>" CTA and status in the header',
      'Split /projects into Products and Writing & case studies via a new kind field on Project',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/projects-section-dispatch-thesis',
  },
  {
    version: '1.17.0',
    date: '2026-08-11',
    title: 'New Role at ADAPTOVATE',
    description: 'Updated experience across the site for the move to ADAPTOVATE in New York as Lead Product Designer.',
    changes: [
      'Added ADAPTOVATE (Lead Product Designer, New York, Jun 2026 – Present) as the current role in the CV data',
      'Closed out the EnterpriseAI period at May 2026 and switched its copy to past tense',
      'Updated the CV title and location to Lead Product Designer, New York, USA',
      'Refreshed the LLM context so the chat answers with the current role',
      'Added ADAPTOVATE to the homepage experience timeline and defaulted the experience dialog to it',
      'Normalised every role period to abbreviated month + year and aligned the homepage dates with the CV data',
    ],
    aiTools: ['Claude Code'],
  },
  {
    version: '1.16.1',
    date: '2026-03-21',
    title: 'Fix FAB White Rectangle',
    description: 'Fixed the floating chat avatar button showing a white rectangle behind it in light mode.',
    changes: [
      'Added rounded-full to the FAB button element so the shadow and background clip to a circle',
      'Applied fix across all pages (home, contact, how-i-work, cv, projects)',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-fab-background',
  },
  {
    version: '1.16.0',
    date: '2026-02-27',
    title: 'Animated Accent SVG Cards',
    description: 'Gave project card SVGs the same accent colour treatment as the GitHub contributions grid — draw-in animation with varying accent opacities.',
    changes: [
      'SVG paths now draw in with staggered pathLength animation on scroll',
      'Each SVG element uses a different accent opacity (0.3–1.0) matching the contribution grid range',
      'Workflow circles have subtle accent fills that intensify left-to-right',
      'Sparkle rays animate outward from center with decreasing opacity',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/accent-svg-project-cards',
  },
  {
    version: '1.15.0',
    date: '2026-02-24',
    title: 'Warmth Mode',
    description: 'Added a warmth toggle to the theme selector that shifts the neutral palette to warmer tones, like f.lux for the website.',
    changes: [
      'Added warm mode toggle in theme selector dropdown with Flame icon',
      'Light warm: creamy off-white background and softened text',
      'Dark warm: warm dark grey background instead of pure black',
      'Warmth persists via localStorage and applies before hydration to prevent flash',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/add-warmth-theme',
  },
  {
    version: '1.14.0',
    date: '2026-02-20',
    title: 'Animated Signature Component',
    description: 'Added an animated cursive signature that reveals with a writing effect, shown in page footers and the about section.',
    changes: [
      'Created Signature component with Caveat handwriting font and clip-path reveal animation',
      'Added signature to footer on home, CV, and How I Work pages',
      'Added signature below about section on homepage',
      'Added Caveat Google Font as --font-signature CSS variable',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/add-signature',
  },
  {
    version: '1.13.0',
    date: '2026-02-17',
    title: 'Case / Visual Tab Toggle on Project Pages',
    description: 'Added a tab group to project pages that lets visitors quickly switch between the full case study and a visual-only gallery of all media.',
    changes: [
      'Added Case/Visual tab toggle below the project header on pages with media content',
      'Visual mode shows only images, videos, embeds, and GIFs with section headings for context',
      'Tab only appears on projects that contain media blocks',
      'Table of contents hidden in visual mode',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/case-study-visual-tabs',
  },
  {
    version: '1.12.0',
    date: '2026-02-13',
    title: 'Facehash Avatar Styling & Identity Notification',
    description: 'Circular facehash avatars and a system notification when visitors receive their facehash identity.',
    changes: [
      'Made Gareth\'s chat header avatar circular to match facehash style',
      'Made user chat avatars circular',
      'Added system notification when a visitor\'s name is detected, telling them they\'ve been given a facehash identity',
      'Small facehash preview shown inline with the identity notification',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/facehash-avatars',
  },
  {
    version: '1.11.1',
    date: '2026-02-13',
    title: 'Remove Thinker Name Hover Effect',
    description: 'Removed misleading hover styling from product thinker names since the cards are not clickable.',
    changes: [
      'Removed group-hover:text-accent from thinker name heading',
      'Removed group class from ThinkerCard container',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-thinker-hover',
  },
  {
    version: '1.11.0',
    date: '2026-02-13',
    title: 'Live GitHub Contribution Count',
    description: 'Contribution count now syncs live from the GitHub GraphQL API while the heatmap keeps its narrative arc.',
    changes: [
      'Contribution count fetches live total (public + private) from GitHub API',
      'Changed label from "commits" to "contributions" to match GitHub terminology',
      'Removed duplicate CONTRIBUTION_MONTHS from project detail page, uses shared component',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/live-github-commits',
  },
  {
    version: '1.10.4',
    date: '2026-02-13',
    title: 'Subtler Chat Bubbles',
    description: 'Chat message backgrounds now use a color-mix approach for a subtler appearance in both light and dark mode.',
    changes: [
      'Replaced flat bg-border with color-mix(foreground 5%, background) for assistant messages',
      'Dark mode: barely lifted off the dark surface instead of noticeable grey',
      'Light mode: near-white instead of wireframe grey',
      'Applied to welcome message, conversation bubbles, and loading state',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-dark-msg-color',
  },
  {
    version: '1.10.3',
    date: '2026-02-13',
    title: 'Softer CTA Buttons in Dark Mode',
    description: 'Reduced brightness of primary CTA buttons in dark mode for a less harsh appearance against the dark background.',
    changes: [
      'Added --accent-cta CSS variable that darkens the accent by 15% in dark mode',
      'Applied to all primary CTA buttons across homepage, CV, contact, projects, and content dialogs',
      'Light mode CTA buttons remain unchanged',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/darker-cta-dark-mode',
  },
  {
    version: '1.10.2',
    date: '2026-02-12',
    title: 'Experience Dialog Two-Column Layout & Inline Case Studies',
    description: 'Restructured the experience dialog to a two-column layout with full-height chat, and replaced project card links with inline scrollable case study sections.',
    changes: [
      'Changed dialog from stacked (header/content/footer) to two-column layout',
      'Column 1 contains header tabs and scrollable content',
      'Column 2 (GarethLLM chat) now spans the full height of the dialog',
      'Moved close button into the chat panel header',
      'Removed redundant footer navigation since tab group already handles company switching',
      'Replaced project card grid with inline case study sections per project',
      'Each case study has title, description, hero image, detail screenshots, and workflow placeholders',
      'Added View full case study links for each project',
      'Dialog background slightly lighter than base layer for elevated surface feel',
      'Added "Work Experience" title to dialog header',
      'Company tabs now sticky at top of scrollable content',
      'Removed separator from GarethLLM chat header',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/experience-dialog-layout',
  },
  {
    version: '1.10.1',
    date: '2026-02-13',
    title: 'LinkedIn Links on Testimonials',
    description: 'Colleague names in the testimonial carousel now link to their LinkedIn profiles.',
    changes: [
      'Added LinkedIn URLs to all five testimonial entries',
      'Testimonial names render as links that open LinkedIn in a new tab',
      'Hover state uses accent color for consistency with site theme',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/linkedin-testimonials',
  },
  {
    version: '1.10.0',
    date: '2026-02-12',
    title: 'Facehash Chat Avatars',
    description: 'Added deterministic facehash avatars to the GarethLLM chat. Gareth gets a consistent avatar, and visitors get their own unique face after telling GarethLLM their name.',
    changes: [
      'Integrated facehash package for deterministic avatar generation from names',
      'Gareth avatar (with blinking eyes) shown on all assistant messages and loading state',
      'GarethLLM welcome message asks visitors for their name',
      'Name extraction via [[name:X]] tag parsed from LLM responses',
      'Visitor name persisted in localStorage — returning visitors get greeted by name',
      'Visitor facehash avatar appears on their messages once name is known',
      'All existing suggested and follow-up questions preserved',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/facehash-chat-avatars',
  },
  {
    version: '1.9.0',
    date: '2026-02-12',
    title: 'Experience Dialog Carousel',
    description: 'Clickable company names in the Experience section now open a dialog carousel showing company synopsis, key achievements, and related case study links.',
    changes: [
      'New ExperienceDialog component with carousel navigation between companies',
      'Company names in Experience section are now clickable on both homepage and CV page',
      'View button opens dialog starting at most recent company (EnterpriseAI)',
      'Arrow keys and tab navigation to browse between companies',
      'Added placeholder case studies for Daisy Assist, Daisy Assess, SEEK, and Best Practice',
      'Projects linked to companies via companyId field',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/experience-case-studies',
  },
  {
    version: '1.8.4',
    date: '2026-02-12',
    title: 'Testimonial Carousel Scroll Indicators',
    description: 'Added dot indicators and arrow navigation to the testimonial carousel for clearer scroll affordance.',
    changes: [
      'Added dot pagination indicators below testimonial cards',
      'Added left/right chevron arrow buttons for navigation',
      'Left arrow hidden when at the start, right arrow hidden at the end',
      'Extracted shared TestimonialCarousel component used on both home and CV pages',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/scroll-indicators',
  },
  {
    version: '1.8.3',
    date: '2026-02-12',
    title: 'GarethLLM Open by Default on All Pages',
    description: 'Chat sidebar now opens immediately on all pages except homepage, which keeps its animation delay.',
    changes: [
      'Thinkers page: chat opens by default instead of after 1.5s delay',
      'Project pages: chat opens by default instead of waiting for useEffect',
      'Mobile: chat still stays closed on small screens',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-open-all-pages',
  },
  {
    version: '1.8.2',
    date: '2026-02-12',
    title: 'Intercom-style Chat Input & Bubbles',
    description: 'Redesigned chat input and message bubbles to match Intercom/Fin style.',
    changes: [
      'Combined input field and send button into a single bordered container',
      'Replaced "Send" text button with a circular ArrowUp icon button',
      'Switched to multiline textarea with auto-resize (Enter to send, Shift+Enter for new line)',
      'Increased chat bubble border radius to match Fin-style rounded bubbles with tail corners',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-input-redesign',
  },
  {
    version: '1.8.1',
    date: '2026-02-12',
    title: 'Auto-open GarethLLM Chat',
    description: 'GarethLLM chat sidebar now automatically opens after the hero typewriter animation and tooltip complete.',
    changes: [
      'Chat opens automatically after Product Orchestrator animation sequence finishes',
      'Removed separate chat mount timer in favor of sequenced timing tied to animation completion',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/auto-open-chat',
  },
  {
    version: '1.8.0',
    date: '2026-02-08',
    title: 'Article Table of Contents',
    description: 'Added a Substack-style table of contents for case study articles with inline collapsible TOC and a fixed sidebar TOC that appears when scrolling.',
    changes: [
      'Inline TOC at top of article with collapsible heading list (Contents toggle)',
      'Fixed sidebar TOC rendered outside main container to avoid overflow clipping',
      'Compact abstract lines on left border indicate sections, expand to full panel on click',
      'Active heading tracking via IntersectionObserver',
      'Click-to-scroll navigation with smooth scrolling',
      'Escape and click-outside to close expanded panel',
      'Responsive: hidden on mobile, visible on lg+ screens',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/article-toc',
  },
  {
    version: '1.7.0',
    date: '2026-02-08',
    title: 'Dynamic GitHub Commit Count',
    description: 'Live commit count fetched from GitHub API with a count-up animation.',
    changes: [
      'Added API route to fetch real contribution count from GitHub GraphQL API',
      'Count-up animation rolls numbers from 0 using framer-motion springs',
      'Server-side caching (1 hour TTL) to avoid GitHub rate limits',
      'Graceful fallback to static count when API is unavailable',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/animate-commit-count',
  },
  {
    version: '1.6.6',
    date: '2026-02-08',
    title: 'Neutral Chat Input Styling',
    description: 'Removed accent color from chat send button and input focus, using Fin-style neutral black/white theming instead.',
    changes: [
      'Send button: black in light mode, white in dark mode; grayed out when disabled',
      'Chat input focus uses standard ring style instead of accent-colored border',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/chat-send-btn-muted',
  },
  {
    version: '1.6.5',
    date: '2026-02-08',
    title: 'Typewriter Hero & Commit Count',
    description: 'Added typewriter role animation on homepage and commit count above the GitHub contribution graph.',
    changes: [
      'Typewriter effect: Designer → Designer? → Engineer? → Orchestrator',
      'Trademark disclaimer tooltip on Orchestrator with shadcn tooltip',
      'Computed and displayed 872 commits in last 12 months above contribution graph',
      'Added GitHub profile outline button next to primary CTA',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/homepage-commit-count',
  },
  {
    version: '1.6.4',
    date: '2026-02-08',
    title: 'Default Dark Mode with No Flash',
    description: 'Changed the default theme to dark mode for a stronger first impression on portfolio visitors, and eliminated the flash of light mode on page load.',
    changes: [
      'Default theme changed from system to dark mode for new visitors',
      'Added inline blocking script to set dark class before first paint, preventing white flash',
      'Server-rendered HTML now includes dark class on html element',
      'Existing user preferences (light/system) are still respected via localStorage',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/default-dark-mode',
  },
  {
    version: '1.6.3',
    date: '2026-02-08',
    title: 'Fix chat sidebar scroll bug',
    description: 'Fixed a bug where opening the chat sidebar caused the main page content to scroll down unexpectedly.',
    changes: [
      'Replaced scrollIntoView() with direct scrollTop manipulation to prevent scroll from bubbling to parent containers',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-chat-scroll-bug',
  },
  {
    version: '1.6.2',
    date: '2026-02-08',
    title: 'Subtle Accent Treatment for Selection & Chat FAB',
    description: 'Replaced bright accent backgrounds with a subtle muted treatment using color-mix() for text selection and the floating chat button.',
    changes: [
      'Added --selection-bg and --selection-text CSS variables using color-mix() for light and dark modes',
      'Text selection now uses muted accent background with medium-toned accent text',
      'Floating chat button across all 6 pages uses the same subtle treatment',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/subtle-text-selection',
  },
  {
    version: '1.6.1',
    date: '2026-02-08',
    title: 'Fix Button Gravity When Particle Field Off',
    description: 'Fixed a bug where the magnetic cursor-pull effect on buttons remained active even when the particle field feature flag was disabled.',
    changes: [
      'Added disabled prop to Magnetic component that resets offset and skips mouse listener',
      'Linked Magnetic disabled state to the particleField feature flag',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/fix-button-gravity',
  },
  {
    version: '1.6.0',
    date: '2026-02-08',
    title: 'Interactive Venn Diagram Skills Section',
    description: 'Replaced the flat skills list with an interactive 3-circle Venn diagram (Product, Design, Engineering) to showcase cross-disciplinary skills.',
    changes: [
      'Moved skills section from below header to just above testimonials',
      'Added interactive SVG Venn diagram with Product, Design, and Engineering circles',
      'Click any region (single, overlap, or center) to filter skills to that intersection',
      'Two-column layout: Venn diagram (2/3) with scrollable skill tags (1/3)',
      'Gradient borders on multi-zone skills using background-clip trick for rounded corners',
      'Multi-zone title shows each zone name in its own color',
      'Scroll-to-top on CV page mount to fix navigation issue',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/cv-skills-reposition',
  },
  {
    version: '1.5.0',
    date: '2026-02-08',
    title: 'Blog → Changelog',
    description: 'Replaced the blog page with a concise changelog. Moved route from /blog to /changelog, stripped the long-form article, and kept just the version timeline.',
    changes: [
      'Renamed /blog route to /changelog',
      'Removed blog article and markdown renderer — page now shows only the version timeline',
      'Updated header nav and feed links to point to /changelog',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/blog-to-changelog',
  },
  {
    version: '1.4.0',
    date: '2026-02-08',
    title: '2x2 Bento Projects Grid',
    description: 'Replaced the horizontal auto-scrolling projects carousel with a 2x2 bento grid showcasing 4 curated case studies with SVG illustrations.',
    changes: [
      'Replaced horizontal carousel with 2x2 bento grid layout (responsive: stacks on mobile)',
      'Added themed SVG illustrations per card: GitHub heatmap, code brackets, workflow nodes, sparkle',
      'Curated 4 featured projects: The Future is Now, Respond to RFP, How I Work, Conjure Your Own Tools',
      'Added numbered cards (01-04) and "View all" link to /projects',
      'Removed carousel auto-scroll, dot indicators, and related state management',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/bento-projects-grid',
  },
  {
    version: '1.3.0',
    date: '2026-02-06',
    title: 'Interactive Hero & Scroll Animations',
    description: 'Added an interactive particle constellation canvas to the hero section, magnetic hover effects on CTAs, and converted all below-fold sections to scroll-triggered reveal animations.',
    changes: [
      'Built canvas-based particle field with organic flow, mouse attraction, spotlight glow, and accent-color-aware rendering',
      'Particles connect with distance-based lines and pulse with breathing opacity',
      'Added Magnetic wrapper component for satisfying cursor-follow hover effects on buttons',
      'Converted About, Projects, Experience, Thinkers, and Testimonials to scroll-triggered `whileInView` animations',
      'Respects `prefers-reduced-motion` and adapts particle count for mobile devices',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/wow-interactive-hero',
  },
  {
    version: '1.2.0',
    date: '2026-02-05',
    title: 'Feed View',
    description: 'Added a new /feed route that aggregates all content types into a filterable, scrollable feed.',
    changes: [
      'Created /feed page with vertical scrollable feed of all content',
      'Unified feed items from projects, thinkers, and changelog entries',
      'Added sticky filter bar with content type and tag filtering',
      'Created FeedCard component with type-specific rendering',
      'Extracted CHANGELOG to shared /src/content/changelog.ts',
      'Added Feed link to Header navigation',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/mobile-feed-view',
  },
  {
    version: '1.1.0',
    date: '2026-02-05',
    title: 'New Essay: You Can Conjure Your Own Tools Now',
    description: 'Added a new article about how AI coding tools change creative practice — building custom tools on demand and preserving design iterations as living artifacts.',
    changes: [
      'Published essay on creative tooling and the shift from waiting for features to conjuring them',
      'Explores using feature branches and flags as a design canvas for iteration history',
      'New project entry accessible from the projects page',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/creative-tooling-post',
  },
  {
    version: '1.0.0',
    date: '2026-02-05',
    title: 'New Essay: The GUI Has to Earn Its Place',
    description: 'Added a new article exploring how chat interfaces are changing expectations for GUIs. Chat API now supports Anthropic for production.',
    changes: [
      'Published essay on changing expectations for GUIs in the age of chat',
      'New project entry accessible from the projects page',
      'Chat API supports Anthropic Haiku 4.5 in production, Groq in dev',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/Gui-essay',
  },
  {
    version: '0.9.0',
    date: '2026-02-05',
    title: 'Product Thinkers',
    description: 'Added a new section showcasing product thinkers who have shaped my approach to design and product work.',
    changes: [
      'Created `/thinkers` page with edge-touching card grid',
      'Added homepage preview section between Experience and Testimonials',
      'Features Teresa Torres, Spiek & Moesta, Ryan Singer, and Christopher Alexander',
      'Created thinkers content data model in `/src/content/thinkers.ts`',
      'Created reusable `ThinkerCard` component for homepage use',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/product-thinkers-page',
  },
  {
    version: '0.8.0',
    date: '2026-02-05',
    title: 'RFP Case Study',
    description: 'Built out the "Responding to an RFP" case study page with full narrative content and video placeholders for key feature demonstrations.',
    changes: [
      'Rewrote RFP case study with full narrative: situation, problem, approach, impact, and outcome',
      'Added TLDR section summarizing the one-person-army story',
      'Added 5 video placeholder sections for key feature demos (seed data, LLM chat, scale adaptation, rapid iteration, interactive workflows)',
      'Structured before/after impact comparison (without AI vs with AI)',
      'Updated project tags, description, and chat context for richer AI sidebar conversations',
    ],
    aiTools: ['Claude Code'],
    branch: 'GChainey/rfp-case-study',
  },
  {
    version: '0.7.0',
    date: '2026-01-24',
    title: 'Edge-Touching Cards & Feature Flags',
    description: 'Major visual refinement with cleaner card layouts and developer tools for design iteration.',
    changes: [
      'Implemented edge-touching card style (no gaps, shared borders)',
      'Added feature flag system with Cmd+K drawer for toggling design options',
      'Created shared GitHubContributions component for reuse across pages',
      'Testimonials now show as horizontal carousel (2 visible at a time)',
      'Projects page matches homepage shell styling with border-x',
      'Section title borders toggleable via feature flag',
      'Removed chat input border for cleaner alignment',
      'Added Experience section with timeline visualization',
      'Added Testimonials section with colleague quotes',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
    images: [
      '/blog/v7-homepage-light.png',
      '/blog/v7-homepage-dark.png',
      '/blog/v7-projects-light.png',
      '/blog/v7-projects-dark.png',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-01-24',
    title: 'Theme System Overhaul & System Mode',
    description: 'Complete redesign of theming with accent colors and system preference support.',
    changes: [
      'Added theme dropdown with System/Day/Night mode options',
      'System mode automatically follows OS light/dark preference',
      'Added 16 Tailwind accent colors (amber, orange, red, rose, etc.)',
      'Accent color persists to localStorage',
      'Real-time system preference change detection',
      'Default to System mode with Amber accent',
    ],
    aiTools: ['Claude Code'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.5.0',
    date: '2026-01-24',
    title: 'ElevenLabs UI & Shimmering Effects',
    description: 'Integrated ElevenLabs UI components for enhanced loading states.',
    changes: [
      'Added ShimmeringText component for loading states',
      'TLDR generation button shows shimmering "Generating summary..." text',
      'Chat interface uses shimmering "Thinking..." for AI responses',
      'Smooth shimmer animation with customizable colors',
    ],
    aiTools: ['Claude Code', 'ElevenLabs'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.4.0',
    date: '2026-01-24',
    title: 'Chat Enhancements & Shared Components',
    description: 'Added project cards in chat and extracted shared components.',
    changes: [
      'Chat can now include project cards using [[project:id]] syntax',
      'Created shared Header component for consistent navigation',
      'Added hover accent colors on project card titles and arrows',
      'Fixed scroll-to-top behavior on article pages',
      'Added "Back to top" button in footers',
      'Fixed double border issues between sections',
      'Fixed dropdown transparency with proper bg-background',
    ],
    aiTools: ['Claude Code'],
    branch: 'feature/articles-and-improvements',
  },
  {
    version: '0.3.0',
    date: '2026-01-24',
    title: 'Two-Column Layout & Chat Sidebar',
    description: 'Major redesign focusing on storytelling and AI transformation narrative.',
    changes: [
      'Redesigned to two-column layout (main content + chat sidebar)',
      'Added "Gareth Chainey" as permanent title with animated role subtitle',
      'Created GitHub contributions visualization showing 2024→2025 transformation',
      'Implemented experience timeline with brand-colored highlights',
      'Updated chat interface with black bubbles in day mode',
      'Added Lucide icons for theme toggle (Sun/Moon)',
    ],
    aiTools: ['Claude Code', 'Agentation'],
    branch: 'feature/layout-v2-two-column-chat',
    pr: 'https://github.com/GChainey/portfolioWebsite/pull/2',
  },
  {
    version: '0.2.0',
    date: '2026-01-24',
    title: 'Theme System & GitHub Integration',
    description: 'Added dark/light mode theming and live GitHub activity feed.',
    changes: [
      'Implemented ThemeContext with system preference detection',
      'Added localStorage persistence for theme choice',
      'Created GitHubActivity component fetching live data',
      'Built contribution graph visualization',
      'Added recent activity feed with formatted dates',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
  },
  {
    version: '0.1.0',
    date: '2026-01-24',
    title: 'Initial Scaffolding',
    description: 'Set up the foundational project structure with Next.js 14.',
    changes: [
      'Initialized Next.js 14 with TypeScript and Tailwind CSS',
      'Configured Framer Motion for animations',
      'Set up Anthropic SDK for AI chat integration',
      'Created edge-to-edge grid layout system',
      'Built initial component structure',
    ],
    aiTools: ['Claude Code'],
    branch: 'main',
    image: '/blog/v1-grid-layout.png',
  },
]
